# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ik0veFT4M8fuZ2eey51SI3ZkDjlB47_e
"""

import cv2
import numpy as np
!pip install ultralytics
from ultralytics import YOLO

import numpy as np
!pip install filterpy
from filterpy.kalman import KalmanFilter

class Tracker:
    def __init__(self, bbox, track_id):
        self.bbox = bbox
        self.id = track_id

class SimpleSORT:
    def __init__(self):
        self.trackers = []
        self.next_id = 0

    def update(self, detections):
        updated_tracks = []

        for det in detections:
            x1, y1, x2, y2 = det

            matched = False
            for tr in self.trackers:
                tx1, ty1, tx2, ty2 = tr.bbox

                iou = self.compute_iou(det, tr.bbox)

                if iou > 0.3:
                    tr.bbox = det
                    updated_tracks.append(tr)
                    matched = True
                    break

            if not matched:
                new_tracker = Tracker(det, self.next_id)
                self.next_id += 1
                updated_tracks.append(new_tracker)

        self.trackers = updated_tracks
        return self.trackers

    def compute_iou(self, boxA, boxB):
        xA = max(boxA[0], boxB[0])
        yA = max(boxA[1], boxB[1])
        xB = min(boxA[2], boxB[2])
        yB = min(boxA[3], boxB[3])

        interArea = max(0, xB - xA) * max(0, yB - yA)

        boxAArea = (boxA[2]-boxA[0])*(boxA[3]-boxA[1])
        boxBArea = (boxB[2]-boxB[0])*(boxB[3]-boxB[1])

        iou = interArea / float(boxAArea + boxBArea - interArea + 1e-5)

        return iou

model = YOLO("yolov8n.pt")

tracker = SimpleSORT()

cap = cv2.VideoCapture(0)

while True:

    ret, frame = cap.read()
    if not ret:
        break

    results = model(frame)

    detections = []

    for r in results:
        boxes = r.boxes.xyxy.cpu().numpy()

        for box in boxes:
            x1, y1, x2, y2 = map(int, box[:4])
            detections.append([x1, y1, x2, y2])

    tracks = tracker.update(detections)

    for tr in tracks:
        x1, y1, x2, y2 = map(int, tr.bbox)
        track_id = tr.id

        cv2.rectangle(frame, (x1,y1), (x2,y2), (0,255,0), 2)

        label = f"ID {track_id}"
        cv2.putText(frame, label, (x1, y1-10),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.6, (0,255,0), 2)

    cv2.imshow("Object Detection & Tracking", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()